Adapt to coq/coq#15802
mit-plv/fiat pull request #68
Opened 2022-03-16 13:52 UTC by proux01

2022-03-16 16:49 UTC, JasonGross requested changes

2022-03-16 16:49 UTC, JasonGross commented on src/Parsers/BaseTypes.v
> +  #[export] Existing Instance split_data.
This is not backwards compatible, try `Global` instead?  Or unprefixed?

2022-03-16 16:51 UTC, proux01 commented on src/Parsers/BaseTypes.v
> +  #[export] Existing Instance split_data.
Indeed, the current behavior is `Global`, my bad.

2022-03-16 16:57 UTC, JasonGross commented on src/Common/Tactics/HintDbExtra.v
> +Declare ML Module "coq-fiat-parsers.hint_db_extra_plugin".
Did you intend to change this?  This seems like an unrelated change

2022-03-16 17:01 UTC, proux01 commented on src/Common/Tactics/HintDbExtra.v
> +Declare ML Module "coq-fiat-parsers.hint_db_extra_plugin".
Indeed not.

2022-03-17 04:41 UTC, JasonGross approved these changes

2022-03-17 04:42 UTC, JasonGross commented
For some reason CI did not run (AFAICT), I will close and re-open to see if that makes it run

2022-03-17 20:02 UTC, proux01 commented
@JasonGross thanks, CI green

2022-03-17 22:02 UTC, merged